spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: pro

#application.yaml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    lazy-loading-enabled: true

comment.avatar: /images/avatar.png

